/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackupCard: typeof import('./components/backup/BackupCard.vue')['default']
    BackupListItem: typeof import('./components/backup/BackupListItem.vue')['default']
    BackupManager: typeof import('./views/BackupManager.vue')['default']
    CommandOutputDialog: typeof import('./components/dialogs/CommandOutputDialog.vue')['default']
    ProjectCard: typeof import('./components/project/ProjectCard.vue')['default']
    ProjectDialog: typeof import('./components/project/ProjectDialog.vue')['default']
    ProjectListItem: typeof import('./components/project/ProjectListItem.vue')['default']
    ProjectManagerPage: typeof import('./views/ProjectManagerPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerCard: typeof import('./components/server/ServerCard.vue')['default']
    ServerDialog: typeof import('./components/server/ServerDialog.vue')['default']
    ServerListItem: typeof import('./components/server/ServerListItem.vue')['default']
    ServerManagementPage: typeof import('./views/ServerManagementPage.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SshTerminal: typeof import('./views/SshTerminal.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
